### ISSUE TITLE
i18n: activerecord attributes only translates form fields

### ISSUE THREAD

**Issue by dfang** [thoughtbot/administrate#1180]
```
zh-CN:
    activerecord:
       atrributes:
           user:
              nickname: 昵称
```

only translates form fields in  `admin/user/1/edit `,  not fields in `admins/users` and `admin/users/1`.

thanks !

**Comment by Samemura** [comment]
It needs to be different definition like:
```
en:
  helpers:
    label:
      customer:
        name: Full Name
```

For the detail, please refer to https://administrate-prototype.herokuapp.com/customizing_dashboards
