### ISSUE TITLE
Resource names are not being translated properly on notice messages

### ISSUE THREAD

**Issue by rscardinho** [thoughtbot/administrate#1242]
The resource model name isn't being translated when you execute a DB transaction (create, for example). The whole message is translated according to the `yml` file but the resource model name.

I believe the problem relies on `ResourceReolver#resource_title`, which just parses the current path and returns a `joined` string. The `#translate_with_resource` (the method that translated the message itself) should use `ResourceReolver#resource_class` combined with ActiveRecord locale methods to return the resource model name already localized to the message _translator_ method

This is the message that I'm getting
![image](https://user-images.githubusercontent.com/3933421/49109130-14dc2c80-f271-11e8-994f-a85d95c8895b.png)

And my `yml` file does have that model translation entry
```
pt-BR:
  activerecord:
    models:
      transaction_category:
        one: 'Natureza de Transação'
        other: 'Naturezas de Transação'
```

This problem is happening with other resources around my admin section
