### ISSUE TITLE
Change search placeholder on a dashboard?

### ISSUE THREAD

**Issue by connor** [thoughtbot/administrate#1710]
Hey there,

**Huge** fan of Administrate; thank you!

Is there any way to easily change the search placeholder on a Dashboard? Let's say I have a model, `Article`. Right now it says `Search Articles`. I'd like to change that.

Is that possible?

Thanks!

**Comment by bekicot** [comment]
Change it in your locale:
```yml
# en.yml
administrate:
  search:
    label: Search Article
```
