### ISSUE TITLE
ul/ol symbols are missing for Field::RichText

### ISSUE THREAD

**Issue by sedubois** [thoughtbot/administrate#1856]
* What were you trying to do?

I want to render rich text with Field::RichText, which contains ordered and unordered lists.

* What did you end up with (logs, or, even better, example apps are great!)?

Administrate is [configured](https://github.com/thoughtbot/administrate/blob/33a46ffce8a3f42047ce0ac4980699a659c52f40/app/assets/stylesheets/administrate/base/_lists.scss#L3) with a default `list-style-type: none`. Because of this, ordered ad unordered lists are displayed without any symbol:

<img width="340" alt="Screenshot 2020-12-31 at 11 25 49" src="https://user-images.githubusercontent.com/4217871/103406422-f4bb7d80-4b5a-11eb-98bc-0308d5d6553b.png">

This could be fixed by CSS :

```css
.trix-content {
  ul {
    list-style-type: disc;
  }
  ol {
    list-style-type: decimal;
  }
}
```

* What versions are you running?
  - Rails 6.1.0
  - administrate 0.14.0
