### ISSUE TITLE
Add the locale setting method of the table column.

### ISSUE THREAD

**Issue by bino98** [thoughtbot/administrate#1928]
Hi. Thank you for reading this.

I want to using Japanese locale in table header column. but I don't know how to change header columns locale.
I tried to set activerecord locales as follow.

```yaml
ja:
  activerecord:
    models: &models
      company: 会社
      employee: 従業員
      ...
```

Actually, It's displayed correctly in side menu labels.

<img width="815" alt="従業員_-_App" src="https://user-images.githubusercontent.com/353699/109901134-d9482c80-7cdb-11eb-916d-c1241fb00bde.png">

Is there any good way?

**Comment by pablobm** [comment]
I think that the problem here is about the difference between models and attributes. In your app, `Company` is a model, but it is also an attribute of `Employee` (as a belongs_to association). Models and attributes are translated separately.

Following the [Rails guides on this topic][rails guides], I believe you need to do the following:

```
ja:
  activerecord:
    models: &models
      company: 会社
      employee: 従業員
      ...
    attributes:
      employee:
        company: 会社
```

Does that fix the issue?

[rails guides]: https://guides.rubyonrails.org/i18n.html#translations-for-active-record-models
