### ISSUE TITLE
How to render dashboard fields based on condition

### ISSUE THREAD

**Issue by DavidGeismarLtd** [thoughtbot/administrate#1949]
* What were you trying to do?
I am building a multitenant app with administrate dashboard field displayed based on the kind of account you subscribed to. I use act as tenant for multitenancy and administrate for dashboard. Each tenant has access to his own dashboard and based on the plan type has more or less fields displayed. Here was my solution to that problem : 

I define a yml file with my dashboard filed config : 
```
collection:
  basic:
    - title
    - author
    - goals
    - program_recommandation
    - publication_status
    - session_subscription_mode
    - upcoming_date
    - position
  essential:
    - title
    - author
    - goals
    - program_recommandation
    - publication_status
    - session_subscription_mode
    - upcoming_date
    - position
  premium:
    - title
    - author
    - goals
    - program_recommandation
    - publication_status
    - session_subscription_mode
    - upcoming_date
    - position
  site:
    - featured
show_page:
  basic:
    - title
    - publication_status
    - image_cover
    - headline
    - description
    - goals
    - argument_ids
    - duration_in_hours
    - author
    - created_at
    - updated_at
  essential:
    - title
    - publication_status
    - image_cover
    - headline
    - description
    - goals
    - argument_ids
    - duration_in_hours
    - author
    - created_at
    - updated_at
    - session_subscription_mode
    - upcoming_date
    - program_recommandation
  premium:
    - title
    - publication_status
    - image_cover
    - headline
    - description
    - goals
    - argument_ids
    - duration_in_hours
    - author
    - created_at
    - updated_at
    - session_subscription_mode
    - upcoming_date
    - program_recommandation
  site:
    - featured
form:
  basic:
    - title
    - publication_status
    - image_cover
    - headline
    - description
    - goals
    - argument_ids
    - duration_in_hours
    - author
  essential:
    - title
    - publication_status
    - image_cover
    - headline
    - description
    - goals
    - argument_ids
    - duration_in_hours
    - author
    - created_at
    - updated_at
    - session_subscription_mode
    - upcoming_date
    - program_recommandation
  premium:
    - title
    - publication_status
    - image_cover
    - headline
    - description
    - goals
    - argument_ids
    - duration_in_hours
    - author
    - created_at
    - updated_at
    - session_subscription_mode
    - upcoming_date
    - program_recommandation
  site:
    - featured
```

I create a config singleton object in intitializer to hold that config `initializer/dashboard_config.rb `: 

```
DashboardsConfig
  .add(:program, program_dashboard_config)
```

I modify my my Dashboard accordingly : 
```

require 'administrate/base_dashboard'

class ProgramDashboard < Administrate::BaseDashboard
  # ATTRIBUTE_TYPES
  # a hash that describes the type of each of the model's fields.
  #
  # Each different type represents an Administrate::Field object,
  # which determines how the attribute is displayed
  # on pages throughout the dashboard.
  ATTRIBUTE_TYPES = {
    image_cover: Field::ActiveStorage,
    author: Field::BelongsTo,
    products: Field::HasMany,
    id: Field::Number,
    title: Field::String.with_options({
                                        searchable: true
                                      }),
    program_recommandation: Field::BelongsTo,
    featured: Field::Boolean,
    headline: Field::String,
    description: Field::Trix,
    goals: Field::Trix,
    duration_in_hours: Field::Number,
    position: Field::Number,
    created_at: Field::DateTime,
    updated_at: Field::DateTime,
    publication_status: Field::Select.with_options(collection: Program.publication_statuses.keys),
    session_subscription_mode: Field::Select.with_options(collection: Program.session_subscription_modes.keys),
    upcoming_date: Field::Date,
    argument_ids: MultipleSelectField.with_options(
      searchable: false,
      display: :description
    )
  }.freeze

  %w[collection show_page form].each do |page|
    define_singleton_method "#{page}_attributes" do
      config = DashboardsConfig.instance.find_by_name(:program)
      attributes = config[page]
      tenant = ActsAsTenant.current_tenant
      plan_attributes = tenant ? attributes[tenant.active_plan.name].map(&:to_sym) : []
      plan_attributes += attributes['site'].map(&:to_sym) if tenant&.has_active_site?
      plan_attributes
    end
  end
  # COLLECTION_ATTRIBUTES
  # an array of attributes that will be displayed on the model's index page.
  #
  # By default, it's limited to four items to reduce clutter on index pages.
  # Feel free to add, remove, or rearrange items.
  COLLECTION_ATTRIBUTES = collection_attributes.freeze

  # SHOW_PAGE_ATTRIBUTES
  # an array of attributes that will be displayed on the model's show page.
  SHOW_PAGE_ATTRIBUTES = show_page_attributes.freeze

  # FORM_ATTRIBUTES
  # an array of attributes that will be displayed
  # on the model's form (`new` and `edit`) pages.
  FORM_ATTRIBUTES = form_attributes.freeze

  # COLLECTION_FILTERS
  # a hash that defines filters that can be used while searching via the search
  # field of the dashboard.
  #
  # For example to add an option to search for open resources by typing "open:"
  # in the search field:
  #
  #   COLLECTION_FILTERS = {
  #     open: ->(resources) { resources.where(open: true) }
  #   }.freeze
  COLLECTION_FILTERS = {}.freeze

  # Overwrite this method to customize how programs are displayed
  # across all pages of the admin dashboard.
  #
  def display_resource(program)
    program.title
  end
end
```

This approach works locally but when I deploy to heroku in production; seems like my dynamically defined singleton methods (`collection_attributes, show_page_attributes, form_attributes`) always respond [].

Is there a way to achieve conditional rendering of fields in the dashboard in this way ?
