### ISSUE TITLE
The has_many render with invalid field translation

### ISSUE THREAD

**Issue by elct9620** [thoughtbot/administrate#2056]
* What were you trying to do?

I have two models `User` and `Merchant`.

```ruby
class Merchant
  belongs_to :referrer, class_name: 'User', optional: true
  has_many :users, through: :memberships
end

class User
  belongs_to :referrer, class_name: 'User', optional: true
end
```

When I show a merchant, the fields display incorrectly for `users`

```yaml
en-US:
  activerecord:
    attributes:
      user:
        referrer: TypeA
      merchant:
        referrer: TypeB 
```

The merchant's referrer field name is `TypeB` and correct, but the users' collection's referrer field displays `TypeB` instead of `TypeA`

* What did you end up with (logs, or, even better, example apps are great!)?

I use the `rails-i18n-debug` gem the list all i81n keys loaded, and check for the `en-US.activerecord.attributes.user.referrer` not loaded.

* What versions are you running?
  - Rails 6.1.4.1
  - administrate 0.16

**Comment by pablobm** [comment]
Thank you for filing this bug. I'm not sure I understand completely. Some questions:

* Can you provide the code of the affected dashboards? At least the relevant fields.
* Can you show a screenshot with the issue? Feel free to change the labels or obscure non-relevant details for privacy.
* When you say that the translation "users" doesn't show correctly, could it be that the key in the i18n should be `users` instead of `user`?

**Comment by elct9620** [comment]
@pablobm 

My i18n files:

```yaml
en-US:
  activerecord:
    attributes:
      user:
        id: 會員編號
        name: 名稱
        referrer: 介紹人
     merchant:
        id: 店家編號
        name: 名稱
        referrer: 展店人
```

I have two models `User` and `Merchant` and they have the same field `referre`.

In the `Merchant` index to list all, the translation is correctly set to `展店人`（`merchant.referrer`）

![截圖 2021-12-03 下午8 32 20](https://user-images.githubusercontent.com/887984/144603637-89914cb2-b0c9-4d37-96ca-bb9f0e039c35.png)

When I open a single `Merchant` show page, the `users` will be listed on this page with dashboard config.

```ruby
ATTRIBUTE_TYPES = {
    owner: Field::BelongsTo,
    referrer: Field::BelongsTo, # 展店人
    id: Field::Number,
    name: Field::String,
    customers: Field::HasMany, # has_many :customers, class_name: 'User', through: :memberships
}.freeze
```

In this case, the `customers` association field name should be `介紹人`(`user.referrer`) instead of `展店人`（`merchant.referrer`）

![截圖 2021-12-03 下午8 32 37](https://user-images.githubusercontent.com/887984/144603979-0b5da5a4-1eb4-431c-924b-cf4bf4fc0d0c.png)

Does this information help to check the bug?

**Comment by pablobm** [comment]
Could it be that the i18n key is "customer" (or "customers") rather than "user"? I can't remember, but I think that ActiveRecord uses the name of the relationship and not the name of the associated class:

```
en-US:
  activerecord:
    attributes:
      customer:
        id: 會員編號
        name: 名稱
        referrer: 介紹人
     merchant:
        id: 店家編號
        name: 名稱
        referrer: 展店人
```

Also, perhaps not relevant, but may I ask why you use the locale `en-US` instead of `jp`?

**Comment by elct9620** [comment]
I will change it and try it again. My `i18n-debug` gem didn't show the `customer` as search options that I guess depends on the associated class.

The example use `en-US` because I forget replace it to `zh-TW` 😅

**Comment by elct9620** [comment]
I had tested it, and it depends on the associated class.

I also find a workaround to add `helpers.label` to let them display correctly

```yaml
zh-TW:
  activerecord:
    attributes:
      user:
        id: 會員編號
        name: 名稱
        referrer: 介紹人
     merchant:
        id: 店家編號
        name: 名稱
        referrer: 展店人
  helpers:
    label:
      user:
        referrer: 介紹人
```

It is still confusing for me, if we display `customers` on the page, it should use `attributes.user` instead `attributes.merchant` but the result refers to the current resource (merchant).
