### ISSUE TITLE
support I18n in navigation block

### ISSUE THREAD

**Issue by jubilee2** [thoughtbot/administrate#2165]
I am open question here. Is that make sense to you guys for use i18n to display table name in navigation?

https://github.com/thoughtbot/administrate/blob/5ef03b940b9ee0b0e521255b1a52860ac2857c11/app/views/administrate/application/_navigation.html.erb#L14

**Comment by jubilee2** [comment]
sorry already support it!
maybe can add document to describe it

i am going to close issue
```
en:
  activerecord:
    models:
      user: 'Customer'
```
