### ISSUE TITLE
How can you change the names of the links in the navigation of the dashboard?

### ISSUE THREAD

**Issue by spacerobotTR** [thoughtbot/administrate#2268]
Instead of scheduleeventtype as the display how to do I make given models read like Schedule Event Type?

**Comment by jubilee2** [comment]
edit yml file in config/local like following example
```yml
en:
  activerecord:
    models:
      user: Customer
    attributes:
      user:
        login: "Handle"
```

you can find information here
[https://guides.rubyonrails.org/i18n.html#translations-for-active-record-models](https://guides.rubyonrails.org/i18n.html#translations-for-active-record-models)
