### ISSUE TITLE
Translations of the resources used in Administrate

### ISSUE THREAD

**Issue by nastia-shaternik** [thoughtbot/administrate#319]
Hi there,

I would like to use translations for resources that used in Administrate.
So, where should I place them?
Thank you in advance for the answer.

P.S.
I've tried to place them in my local `config/locales/administrate.ru.yml`, kinda:

```yaml
---
ru:
  administrate:
    actions:
      confirm: Вы уверены?
      destroy: Удалить
      edit: Редактировать
      show: Показать
    controller:
      create:
        success: "%{resource} был успешно создан."
      destroy:
        success: "%{resource} был успешно удален."
        not_the_last: "Невозможно удалить последний %{resource}."
      update:
        success: "%{resource} был успешно обновлен."
    fields:
      has_many:
        more: "%{count} из %{total_count}"
        none: Нет
      polymorphic:
        not_supported: Полиморфные отношения в формах не поддерживаются.
      has_one:
        not_supported: HasOne отношения в формах не поддерживаются.
    activerecord:
      models:
        cartoon:
          one: Мультик
          other: Мультики
```

Also I tried to add this into `ru.yml`:
```yaml
ru:
  activerecord:
    models:
      cartoon:
        one: Мультик
        other: Мультики
```

But this doesn't help :(.
