### ISSUE TITLE
Custom labels for fields

### ISSUE THREAD

**Issue by Xosmond** [thoughtbot/administrate#451]
Hi, i have some models with short name fields and i want to change the label of some with other more verbose, how can i change the labels of some string fields? Thanks all.

**Comment by eimhin** [comment]
+1

**Comment by atwoodjw** [comment]
You can do this via localization.

config/locales/en.yml
```
en:
  helpers:
    label:
      admin_user:
        password_confirmation: "Confirmation"
```

**Comment by Xosmond** [comment]
I have tried but does not work :confused:. Do you have any project where you have did it to share?

**Comment by graysonwright** [comment]
@Xosmond - I just added a test to verify that @atwoodjw's approach works: https://github.com/thoughtbot/administrate/pull/492

Can you post the code you're using that isn't working?

**Comment by Xosmond** [comment]
Sorry for the late. This solution works only on normal attributes but on relations doesn't work:
en.yml
```
  helpers:
    label:
      control1:
        registro1s: "Registros"
        nombre_documento: "titulo"
```

Here, the "nombre_documento" is a string  attribute of control1 and It works. But "registro1s" is a relation, because control1 has many registro1s and it doesn't work.

Any solution for this?

**Comment by KatherineMuedas** [comment]
I am trying this but it does not work. Do I need to create an administrate.en.yml file inside locales or can I just add it to my en.yml file ?

**Comment by Xosmond** [comment]
Just in the en.yml , make sure you are not using i18n on your config/application.rb

**Comment by KatherineMuedas** [comment]
Ok, In my en.yml file I added this. (school is my model and tuition fee is the attribute )
```
en:
  helpers:
    label:
      school:
        tuition_fee: "Tuition fee average"
```

Is that all I need to make it work ? I am trying to customize the label of the tuition fee attribute.
