### ISSUE TITLE
Dashboard magic?

### ISSUE THREAD

**Issue by micapam** [thoughtbot/administrate#460]
I'm wondering why the dashboards have to declare all the attribute types explicitly. Can't these be inferred from the underlying model, and only declared if they are to be overriden? 

I know we don't need to key these in as they are created by the generator, but it would be nice if the generated dashboard class could be less verbose. And it would be more self-documenting to have an ATTRIBUTE_TYPE_OVERRIDES hash as you could see at a glance which ones aren't the default field types. 

If you agree with what I'm saying I'd be happy to raise a PR. Just wanted to know if you guys can think of a reason the approach I'm suggesting wouldn't work or isn't a good idea...

**Comment by micapam** [comment]
Another way to make the dashboards less verbose would be, instead of three *_ATTRIBUTES arrays, to have a single array with hashes e.g.

```ruby
ATTRIBUTES = [
  foo: { :collection, :show, :form },
  bar: { :show, :form },
  immutable: { :show }
]
```

Or maybe use Rails filters syntax:

```ruby 
ATTRIBUTES = [
  :foo, # i.e. everything
  bar: { except: :collection },
  immutable: { only: :show }
]
```

**Comment by eddietejeda** [comment]
I agree with this. Editing different variables and keeping track of what fields are defined in what variable is cumbersome.

I like all your examples, especially the last one. It resembles the Rails models convention most.

**Comment by graysonwright** [comment]
well, kind of expected this. :stuck_out_tongue_closed_eyes: 

One of the reasons that Administrate is easy to understand and work with is the "No DSLs" guiding principle we started out with (in the README). These proposals would go against that. I'm not entirely opposed to this idea, but I think we should have a significantly pressing reason to break that rule.

We've had discussions about automatically detecting the field type, and decided against it because it would introduce a bit of maintenance overhead. The most notable pitfall is that Administrate would break between major Rails version bumps, because it would be relying on internal API methods to detect the field types

I last talked with @sgrif about this, maybe he has thoughts.

**Comment by micapam** [comment]
I guess the main reason I thought of this change is that the current version doesn't support namespaced models - so I have ended up keying in my own dashboards on my own fork based on @gpinkham's changes. Once administrate does support namespaced models I suppose this will be less of a problem as the generators will take care of it.

I do think the dashboards are quite noisy, though - the generated classes are basically just clusters of data. Another way to approach this without breaking your anti-DSL stance - which I do sympathise with, having hated on ActiveAdmin for a long time! - would be to push this stuff into config. 

````yaml
# config/administrate/my-model.yaml
attributes: 
  foo: 
    field:
      type: string
    access: 
      - collection
      - show
      - form
  bar: 
    field:
      type: number
      options: 
        title: 'Unit Price'
        prefix: '$'
        decimals: 2
        multiplier: 0.0.1
    access: 
      - collection
      - show
# etc
````

... but maybe you would feel like this YAML is a DSL in disguise, haha! :)
