### ISSUE TITLE
i18n helpers.submit translations not taken

### ISSUE THREAD

**Issue by alvaroemmanuel** [thoughtbot/administrate#530]
Hi guys,

I've been working with i18n for my app and so far everything works good with Administrate, but oddly the `helpers.submit` translations in particular are not working. I can't get the app to take them in the New and Edit actions for the admin dashboard.

I installed i18n-debug gem to check out what was going on and found this:

```
[i18n-debug] es.helpers.submit.item.create => nil
[i18n-debug] es.helpers.submit.create => nil
```

Seems that somehow rails is not taking this translation line, though it is only used inside admin dashboard.

The relevant part of my `es.yml` looks like this:

```

---
es:
  activerecord:
    models:
      item:
        one: 'Ítem'
        other: 'Ítems'
      genre:
        one: 'Género'
        other: 'Géneros'
      language:
        one: 'Idioma'
        other: 'Idiomas'
  helpers:
    submit:
      create: "Crear %{model}"
      update: "Actualizar %{model}"
```

I've also tried this with no luck either:

```
  helpers:
    submit:
      item:
        create: "Crear %{model}"
        update: "Actualizar %{model}"
```

Hope you guys can give me some advice on this.

Thanks!
