### ISSUE TITLE
I18N: Attributes labels translation issue

### ISSUE THREAD

**Issue by michaelkl** [thoughtbot/administrate#625]
Hello.

First of all, here's my `locale/ru.yml`:

```
ru:
  activerecord:
    attributes:
      user:
        email: Email
        password: Пароль
        password_confirmation: Пароль ещё раз
        name: Имя
        role: Роль
        provider: OAuth-провайдер
```

Now in my User dashboard on _new/edit_ page (one which got the edit form) labels of attributes are displayed using thier translation from locale/ru.yml, but on _index_ and _show_ pages they are don't!

I've dived in sources and found out that on index page the translation is taken from `helper.label` section, not from the `activerecord.attributes` one.

I think translation sources should be unified all over Administrate pages and using `activerecord.attribues` section looks more straightforward to me.

Thank you.

**Comment by FerPerales** [comment]
@michaelkl I ran into this problem. So far, what I've done to avoid duplicated translations is this:

```ruby

common: &commons
  patient:
    address: 'Direccion'
    weight: 'Peso (kg)'
    height: 'Altura (cm)'
    allergies: 'Alergias'
    patient_antecedents: 'Antecedentes del paciente'
```

And then, include _commons in 

```ruby
es
  activerecord:
    models:
      attributes:
         <<: *commons

```

Hope it helps

**Comment by michaelkl** [comment]
@FerPerales Good workaround until issue will have been fixed! Thank you!

**Comment by fikrikarim** [comment]
Any update on this? Thanks :)

**Comment by nickcharlton** [comment]
I'm closing this as the original issue is quite old and the translations have changed quite a bit since this was opened, please open another if this is still an issue.

**Comment by kaelumania** [comment]
This issue still exists!

**Comment by pablobm** [comment]
Yup; I can reproduce.

I agree this is odd. I wonder what the original intent was, using `helpers.label.RESOURCE_NAME.ATTR_NAME` instead of `activerecord.attributes.RESOURCE_NAME.ATTR_NAME`.

Hm, thinking a bit more, I can see an edge case. In forms, fields will tend to match ActiveRecord attributes. On the other hand, in lists/shows there's a higher chance of showing other things, such as constructed attributes (eg: `Customer#lifetime_value`). I'm not sure if these make sense under `activerecord.attributes.*` (honestly don't know; perhaps it makes sense).

A potential idea would be to use a helper that tries for `helper.label.*`, then fall backs for `activerecord.attributes.*` if missing. I may be overthinking this though. I don't have enough experience with i18n to tell what the conventions are here.

Does anyone have experience with these? /cc @nickcharlton

**Comment by jubilee2** [comment]
@pablobm i think it's fixed on index page right?

**Comment by lubieniebieski** [comment]
hi there!
@pablobm I think that the PR #1064 you mentioned solved the issue partially - I can see a proper behaviour for `show` and `index` actions, however in `form` the i18n doesn't work correctly for `Field::BelongsTo` type. In case of `Field::HasMany` - everything works as expected.

Examples that fails to apply the correct translation inf `form` for `Field::BelongsTo` type:
```yaml
en:
  attributes: 
    user: "Some translation for user belongs_to#1"
```
```yaml
en:
 activerecord:
    attributes:
      post:
        user: "Some translation for user belongs_to#2"
```
