### ISSUE TITLE
I18n of new resource button

### ISSUE THREAD

**Issue by bosskovic** [thoughtbot/administrate#699]
Hi, thanks for a great gem!

It would be nice if the label of new resource button was localized:
https://github.com/thoughtbot/administrate/blob/master/app/views/administrate/application/index.html.erb#L36

Here's one way this could be done:

```
  # app/views/administrate/application/index.html.erb:35
  <%= link_to( t('helpers.label.new_resource', resource_name: display_resource_name(resource_name, count=1), default: "New #{page.resource_name.titleize.downcase}"),
      [:new, namespace, page.resource_name],
      class: "button",
    ) %>
```

```
  # app/helpers/administrate/application_helper.rb:8
  def display_resource_name(resource_name, count=0)
    default = count == 0 ? resource_name.to_s.pluralize.titleize : nil
    localized_name = resource_name.to_s.classify.constantize.model_name.human(count: count, default: default)
  end  
```

```
  # in i18n yaml file:
  en:
    helpers:
      label:
        new_resource: "New %{resource_name}"
```

The proposed change would keep current behaviour as default, so it would be fully backward compatible, and yet it would save those who need to localize the gem from overrriding the views just because of that.

Please let me know if you would accept something like that, and I will prepare a pull request.

**Comment by jbwl** [comment]
+1

**Comment by kuboon** [comment]
I think we would use 'administrate' namespace under i18n localize file.
How about this:

```
en:
  administrate:
    buttons:
      new_resource: "New %{resource_name}"
```
