### ISSUE TITLE
Ensure that Autoprefixer is running on Administrate's CSS

### ISSUE THREAD

**Issue by carlosramireziii** [thoughtbot/administrate#766]
As per @tysongach 

> I’ve confirmed that Autoprefixer is not actually running on our CSS...

Related: 
- #372 
- #366

**Comment by nickcharlton** [comment]
@carlosramireziii Now we've mered in #767, do you think we can confirm and close this?

**Comment by carlosramireziii** [comment]
Is there any way to confirm that it's running? I checked the CSS on the demo app and it seems like there are _some_ prefixes, but I'm not sure if that's 100% guarantee that Autoprefixer is working. 

I'm fine closing this up and re-opening if we discover an issue.

**Comment by nickcharlton** [comment]
I've just updated the demo app. It's been a bit out of sync, so what if you try again?

**Comment by tysongach** [comment]
It appears to be running successfully now. I’m looking at the demo app, and given this input:

```scss
.app-container {
  @include margin(null auto);
  align-items: stretch;
  display: flex;
  max-width: 100em;
  min-height: 100vh;
}
```

…we now get this output:

```css
.app-container {
  margin-right: auto;
  margin-left: auto;
  -webkit-box-align: stretch;
  -ms-flex-align: stretch;
  align-items: stretch;
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  max-width: 100em;
  min-height: 100vh;
}
```
