### ISSUE TITLE
Resource Name

### ISSUE THREAD

**Issue by chrishough** [thoughtbot/administrate#835]
Is there a way to change the Resource Name without overriding the application helper?  

So if we had a table named "users" and we wanted to label it "managers" for example.

**Comment by kuboon** [comment]
how about i18n?
You can specify model name in ``activerecord.models.``

**Comment by chrishough** [comment]
I have confirmed this technique can work, however, it does not rename the button labels i.e. `new user` instead of `new dude`.

**Comment by jcieslar** [comment]
You can try something like this for button labels:
```
en:
  helpers:
    submit:
      user:
        create: 'Create manager'
        update: 'Update manager'
```
